### ISSUE TITLE
Increase Max Image Size

### ISSUE THREAD

**Issue by XiCynx** [MaxxWyndham/Breckfest#5]
Hello! I see back in version 1.1.0 you increased the maximum version size to 8192x8192. Would it be possible to increase the image size again up to 16384x16384? I was looking through your source but did not find a solid variable anywhere to easily make this change. Thanks in advance, or if you can let me know where to look to make this change, I'll happily do so.

**Comment by MaxxWyndham** [comment]
Hey!  Man, this takes me back.

Right, I think the limitation exists when converting from bmap to png/etc, right?  Going to bmap should support any dimensions?

If that is the case, I think the line you need to look at is [line 45 of BMAP.cs](https://github.com/MaxxWyndham/Breckfest/blob/739a453a076dd03c40808ec7d60701fa13fd3987/breckFest/BMAP.cs#L45) `byte[] buff = new byte[134217728];`

Assuming 2 bytes per pixel, 8192x8192x2 would be 134,217,728.  To support the size you're talking about I guess that buffer should be set to `536870912`.

It has been a while since I did this so I might be massively off base here!  Can I leave you to experiment?

**Comment by XiCynx** [comment]
Yes, we actually have a couple people looking at trying to make some enhancements to this as I comment on this. I think what we're looking into is how to compress files into .dds format, as of now breckfest only decompresses .dds to .png or .tiff. Since the game natively uses .dds, it only makes sense to convert to those instead! We're just searching through the code now to see if there is anything in there already that can potentially do the opposite of what it does currently for .dds

**Comment by MaxxWyndham** [comment]
Umm, isn't that just the -raw command?

**Comment by MaxxWyndham** [comment]
Hey @XiCynx , give v1.6.0 a spin.  I've massively improved the speed bmaps are generated, increased the max image size to 16k and added the `-dds` command to export to DDS rather than PNG.  Let me know how you get on.

**Comment by XiCynx** [comment]
It converted my 16384x16384 .tga into a .bmap in about 45 seconds! Amazing! Thank you so much!
